### ISSUE TITLE
jinja2content plugin name / file structure mismatch when used as part of pelican-plugins

### ISSUE THREAD

**Issue by bernieplug** [joachimneu/pelican-jinja2content#2]
The pelican-jinja2content plugin currently diverges from the standard plugin structure, causing a normal plugin include not to work without adding the plugin's directory to "PLUGIN_PATHS"

For example, the other plugins below are successfully included from pelican-plugins, however jinja2content requires adding it to the PLUGIN_PATHS.

PLUGIN_PATHS = ["pelican-plugins",
                os.path.join("pelican-plugins", "pelican-jinja2content"),
                ]
PLUGINS = [
            "assets", # CSS and JS minifier (pip install webassets)
            "sitemap", # yes, we'd like one
            "pelican-page-hierarchy", # URL hierarchy content -> output
            "jinja2content" # gives us ability to use jinja2 in content
          ]

It appears that a consistent plugin name should be chosen (jinja2content or pelican-jinja2content) and that the file structure within the plugin should avoid the extra subdirectory to comply with pelican-plugins standard structure:
https://github.com/getpelican/pelican-plugins/blob/master/Contributing.rst

Thanks for the work on this plugin!

**Comment by joachimneu** [comment]
Thank you! I hope I just fixed this. :)
