### ISSUE TITLE
pelican-jinja2content

### ISSUE THREAD

**Issue by leotrs** [joachimneu/pelican-jinja2content#6]
@joachimneu: this plugin is creating empty `<p>` tags where it shouldn't. I have figured out the cause and a solution.

I notice there hasn't been a lot of development lately. If there is interest, I can prepare a PR. If not, I'm happy with forking and/or creating a new, active, pelican plugin too.

**Comment by joachimneu** [comment]
I am happy to integrate bugfixes and new features with PRs that have been tested, so your contribution would be very welcome.

**Comment by leotrs** [comment]
The solution involved a complete rewrite because I had to render the JInja template at a different time. [Here](https://github.com/leotrs/pelican-jinja2content) is the result.
