### ISSUE TITLE
[Bug] AttributeError: module 'pelican-jinja2content' has no attribute 'register'

### ISSUE THREAD

**Issue by Kristinita** [joachimneu/pelican-jinja2content#7]
### 1. Summary

I can't begin to use pelican-jinja2content. I get traceback.

#### 2.1. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Pelican 3.7.1,
+ Python Markdown 2.6.11.

#### 2.2. Files

[**Part of my `pelicanconf.py` file**](https://github.com/Kristinita/SashaPelicanTest/blob/fc0d5e6b25b8bf61ec3df010e36d79f3e9e4ddd2/pelicanconf.py):

```python
PLUGINS = [
    'pelican-jinja2content',
]

```

If I use another plugins instead of pelican-jinja2content, I haven't errors.

[**Part of my `SashaTest.md` file**](https://github.com/Kristinita/SashaPelicanTest/blob/fc0d5e6b25b8bf61ec3df010e36d79f3e9e4ddd2/content/SashaTest/SashaTest.md) — my example article:

```jinja
{% if article.photo_gallery %}
<div class="gallery">
        {% for title, gallery in article.photo_gallery %}
            <h1>{{ title }}</h1>
                {% for name, photo, thumb, exif, caption in gallery %}
                        <a href="{{ SITEURL }}/{{ photo }}" title="{{ name }}" exif="{{ exif }}" caption="{{ caption }}"><img src="{{ SITEURL }}/{{ thumb }}"></a>
                {% endfor %}
        {% endfor %}
</div>
{% endif %}
```

### 3. Steps to reproduce

I print command in command line:

    pelican content -s pelicanconf.py --debug

### 4. Expected behavior

Successful usage my Jinja2 template in articles.

### 5. Actual behavior

```python
D:\SashaPelicanTest>pelican content -s pelicanconf.py --debug
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.6.4
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `pelican-jinja2content`
DEBUG: Registering plugin `pelican-jinja2content`
CRITICAL: AttributeError: module 'pelican-jinja2content' has no attribute 'register'
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\pelican.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\pelican\__init__.py", line 393, in main
    pelican, settings = get_instance(args)
  File "c:\python36\lib\site-packages\pelican\__init__.py", line 382, in get_instance
    return cls(settings), settings
  File "c:\python36\lib\site-packages\pelican\__init__.py", line 53, in __init__
    self.init_plugins()
  File "c:\python36\lib\site-packages\pelican\__init__.py", line 80, in init_plugins
    plugin.register()
AttributeError: module 'pelican-jinja2content' has no attribute 'register'
```

Thanks.

**Comment by joachimneu** [comment]
I close this because the repository is currently unmaintained. Please check out [the `jinja2content` plugin shipped with `pelican-plugins`](https://github.com/getpelican/pelican-plugins/tree/master/jinja2content).
